Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gambling_my_beloved.Data;
using Gambling_my_beloved.Models;
using Microsoft.AspNetCore.Authorization;

namespace Gambling_my_beloved.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index(string searchQuery)
        {
            IQueryable<Company> companies = this._context.Companies
                .OrderBy(c => c.Name)
                .Select(x => x)
                .Include(c => c.Stocks);

            if (!string.IsNullOrEmpty(searchQuery))
                companies = companies.Where(c => EF.Functions.Like(c.Name, $"%{searchQuery}%"));

            ViewData["SearchQuery"] = searchQuery ?? string.Empty;

            return View(await companies.Take(50).ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Company company = await _context.Companies
                .Where(c => c.Id == id)
                .Include(c => c.Stocks)
                .ThenInclude(s => s.PriceHistory)
                .FirstOrDefaultAsync();
            
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        [Authorize(Roles = Roles.Administrator)]
        public IActionResult Create()
        {
            ViewData["Industries"] = Enum.GetValues<Industry>().Select(i => new SelectListItem(i.GetFriendly(), i.ToString()));
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,CEO,LogoUrl,Industries,Controversy")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["Industries"] = Enum.GetValues<Industry>().Select(i => new SelectListItem(i.GetFriendly(), i.ToString()));

            return View(company);
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            
            ViewData["Industries"] = Enum.GetValues<Industry>().Select(i => new SelectListItem(i.GetFriendly(), i.ToString()));
            
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CEO,LogoUrl,Industries,Controversy")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["Industries"] = Enum.GetValues<Industry>().Select(i => new SelectListItem(i.ToString(), i.ToString()));
            return View(company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.FindAsync(id);
            if (company != null)
            {
                _context.Companies.Remove(company);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }
    }
}

Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gambling_my_beloved.Data;
using Gambling_my_beloved.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;

namespace Gambling_my_beloved.Controllers
{
    public class StocksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public StocksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Stocks
        public async Task<IActionResult> Index(string searchQuery)
        {
            IQueryable<Stock> stocks = this._context.Stocks
                .Include(s => s.Company)
                .Include(s => s.PriceHistory
                    .OrderByDescending(p => p.Date)
                    .Take(2))
                .OrderBy(s => s.Symbol)
                .Select(x => x);

            if (!string.IsNullOrEmpty(searchQuery))
                stocks = stocks.Where(s => EF.Functions.Like(s.Symbol, $"%{searchQuery}%"));
            
            ViewData["SearchQuery"] = searchQuery ?? string.Empty;

            return View(await stocks.Take(50).ToListAsync());
        }

        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Stock stock = await _context.Stocks
                .Include(s => s.Company)
                .Include(s => s.PriceHistory)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (stock == null)
                return NotFound();
            
            string userId = _userManager.GetUserId(User);
            
            StockOwnership stockOwnership = _context.StockOwnerships
                .Include(s => s.Transactions)
                .Include(s=> s.Stock)
                .FirstOrDefault(s => s.StockId == stock.Id && s.AccountId == userId);
            
            ViewData["StockOwnership"] = stockOwnership;
            
            ViewData["StockHistory"] = JsonConvert.SerializeObject(stock.PriceHistory
                .Select(p => new { Date = p.Date, Price = p.Price }));

            return View(stock);
        }

        // GET: Stocks/Create
        [Authorize(Roles = Roles.Administrator)]
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Create([Bind("Id,Symbol,CompanyId,UnitPrice,Volatility,Color")] Stock stock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", stock.CompanyId);
            return View(stock);
        }

        // GET: Stocks/Edit/5
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", stock.CompanyId);
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Symbol,CompanyId,UnitPrice,Volatility,Color")] Stock stock)
        {
            if (id != stock.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", stock.CompanyId);
            return View(stock);
        }

        // GET: Stocks/Delete/5
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .Include(s => s.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stock = await _context.Stocks.FindAsync(id);
            if (stock != null)
            {
                _context.Stocks.Remove(stock);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Transact(int stockId, TransactionType type, int quantity)
        {
            Stock stock = await _context.Stocks
                .Where(s => s.Id == stockId)
                .Include(s => s.PriceHistory)
                .FirstOrDefaultAsync();

            if (stock == null)
                return NotFound();
            
            string userId = _userManager.GetUserId(User);

            StockOwnership stockOwnership = this._context.StockOwnerships
                .Include(stockOwnership => stockOwnership.Account)
                .Include(stockOwnership => stockOwnership.Transactions)
                .FirstOrDefault(s => s.StockId == stock.Id && s.AccountId == userId);
            
            if (stockOwnership == null)
            {
                stockOwnership = new StockOwnership
                {
                    StockId = stock.Id,
                    AccountId = userId,
                    Transactions = new()
                };
                _context.StockOwnerships.Add(stockOwnership);
                
                await _context.SaveChangesAsync();
                
                stockOwnership = this._context.StockOwnerships
                    .Include(s => s.Account)
                    .Include(s => s.Transactions)
                    .FirstOrDefault(s => s.StockId == stock.Id && s.AccountId == userId);
            }
            
            decimal totalCost = quantity * stock.UnitPrice;
            
            Transaction transaction = new()
            {
                StockOwnershipId = stockOwnership.Id,
                StockOwnership = stockOwnership,
                Type = type,
                Quantity = quantity,
                Amount = totalCost,
                Date = DateTime.Now
            };
            
            if (quantity <= 0)
            {
                ViewData["Success"] = false;
                ViewData["Message"] = "Invalid quantity";
                return this.View(transaction);
            }
            
            if (type == TransactionType.Buy)
            {
                if (totalCost > stockOwnership.Account.Balance)
                {
                    ViewData["Success"] = false;
                    ViewData["Message"] = "Insufficient funds";
                    return this.View(transaction);
                }
                
                stockOwnership.Account.Balance -= totalCost;
            }
            else
            {
                if (quantity > stockOwnership.GetQuantity())
                {
                    ViewData["Success"] = false;
                    ViewData["Message"] = "Insufficient stocks";
                    return this.View(transaction);
                }
                
                stockOwnership.Account.Balance += totalCost;
            }
            
            _context.Transactions.Add(transaction);
            
            await _context.SaveChangesAsync();
            
            ViewData["Success"] = true;
            ViewData["Message"] = $"Transaction of {transaction.Amount.ToCurrency()} completed successfully";
            return View(transaction);
        }

        private bool StockExists(int id)
        {
            return _context.Stocks.Any(e => e.Id == id);
        }
    }
}

Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gambling_my_beloved.Data;
using Gambling_my_beloved.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Gambling_my_beloved.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private const int DefaultLimit = 30;
        private const int MaxLimit = 50;

        public TransactionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Transactions
        public async Task<IActionResult> Index(int? offset, int? limit)
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            IQueryable<Transaction> applicationDbContext = _context.Transactions
                .Include(t => t.StockOwnership)
                .ThenInclude(t => t.Stock)
                .ThenInclude(t => t.Company)
                .Where(t => t.StockOwnership.AccountId == user.Id)
                .OrderByDescending(t => t.Date);
                // .Skip(offset ?? 0)
                // .Take(Math.Min(limit ?? DefaultLimit, MaxLimit));
            
            return View(await applicationDbContext.ToListAsync());
        }

        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.Id == id);
        }
    }
}

Views/Stocks/Create.cshtml
@model Gambling_my_beloved.Models.Stock

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Stock</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Symbol" class="control-label"></label>
                <input asp-for="Symbol" class="form-control" />
                <span asp-validation-for="Symbol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label">Company</label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Volatility" class="control-label"></label>
                <input asp-for="Volatility" class="form-control" />
                <span asp-validation-for="Volatility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Stocks/Delete.cshtml
@model Gambling_my_beloved.Models.Stock

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stock</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Symbol)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Model.UnitPrice.ToCurrency()
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Stocks/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Html
@model Gambling_my_beloved.Models.Stock

@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Details";
    bool isSignedIn = SignInManager.IsSignedIn(User);
}

<h1>@Model.Symbol - @Model.Company.Name</h1>
<br/>

<div>
    <h4>Information</h4>
    <hr/>
    <div class="row">
        <div class="col-lg-4 col-12">
            <dl class="row">
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.Symbol)
                </dt>
                <dd class="col-5">
                    <div class="stock-nameplate" style="background-color: @Model.Color">@Model.Symbol</div>
                </dd>
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.Company)
                </dt>
                <dd class="col-5">
                    <a asp-controller="Companies" asp-action="Details" asp-route-id="@Model.Company.Id">
                        @Html.DisplayFor(model => model.Company.Name)
                    </a>
                </dd>
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </dt>
                <dd class="col-5">
                    @Model.UnitPrice.ToCurrency()
                </dd>
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.PriceChange)
                </dt>
                <dd class="col-5">
                    @Model.PriceChange.ToCurrency()
                </dd>
                <dt class="col-5 centerfix-col">
                    @Html.DisplayNameFor(model => model.PriceChangePercent)
                </dt>
                <dd class="col-5">
                    @Html.DisplayFor(model => model.PriceChangePercent, "PriceChangeBubble")
                </dd>
            </dl>
        </div>
        
        <div class="col-lg-4 col-12">
            <dl class="row">
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.Volatility)
                </dt>
                <dd class="col-5">
                    @Html.DisplayFor(model => model.Volatility)
                </dd>
                <dt class="col-5">
                    @Html.DisplayNameFor(model => model.Company.Controversy)
                </dt>
                <dd class="col-5">
                    @Html.DisplayFor(model => model.Company.Controversy)
                </dd>
            </dl>
        </div>

        @if (isSignedIn)
        {
            StockOwnership? stockOwnership = ViewData["StockOwnership"] as StockOwnership;
            int quantity = stockOwnership?.GetQuantity() ?? 0;
            decimal totalInvestment = stockOwnership?.GetTotalInvestment() ?? 0;

            <div class="col-lg-4 col-12">
                <dl class="row">
                    <dt class="col-5">
                        Owned shares
                    </dt>
                    <dd class="col-5">
                        @(quantity.ToString("N0"))
                    </dd>
                    <dt class="col-5">
                        Investment
                    </dt>
                    <dd class="col-5">
                        @totalInvestment.ToCurrency()
                    </dd>
                    <dt class="col-5">
                        Yield
                    </dt>
                    <dd class="col-5">
                        @(stockOwnership != null ? (quantity * Model.UnitPrice).ToCurrency() : "$0.00")
                        @* show percentage increase between total investment and yield *@
                        @if (stockOwnership != null && quantity != 0)
                        {
                            decimal yield = quantity * Model.UnitPrice;
                            decimal percentage = (yield - totalInvestment) / totalInvestment * 100;
                            <span>(</span>
                            @Html.DisplayFor(model => percentage, "PriceChange")
                            <span>)</span>
                        }
                    </dd>
                    <div class="col-5">
                        <a class="btn btn-secondary btn-sm" asp-action="Index" asp-controller="Transactions">
                            Transaction history
                        </a>
                    </div>
                </dl>
            </div>
        }
    </div>

    @if (isSignedIn)
    {
        <h4>New Transaction</h4>
        <hr/>

        <form asp-action="Transact" method="post">
            <input type="hidden" name="stockId" value="@Model.Id"/>

            <div class="row" style="max-width: 500px">
                <div class="col-3">
                    <select name="type" class="form-control">
                        <option value="buy">Buy</option>
                        <option value="sell">Sell</option>
                    </select>
                </div>

                <div class="col">
                    <input type="number" id="quantity" name="quantity" class="form-control" placeholder="Quantity"/>
                </div>

                <div class="col-auto">
                    <input type="submit" value="Transact" class="btn btn-primary"/>
                </div>
            </div>
        </form>
    }

    <br/>

    <h4>History</h4>
    <hr/>

    <div id="chartContainer" style="height: 300px; width: 100%;"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            var result = @Html.Raw(ViewData["StockHistory"]);
            this.console.log(result);

            var DataItem = [];
            for (var i = 0; i < result.length; i++) {
                DataItem.push({
                    x: new Date(result[i].Date),
                    y: result[i].Price,
                });
            }
            
            var chart = new CanvasJS.Chart("chartContainer", {
                zoomEnabled: true,
                animationEnabled: true,
                theme: "light2",
                data: [{
                    markerSize: 0,
                    lineColor: "@Model.Color",
                    markerColor: "@Model.Color",
                    type: "line",
                    dataPoints: DataItem
                }]
            });
            chart.render();
        }
    </script>
</div>
<div>
    @if (User.IsInRole(Roles.Administrator))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> <span> | </span>
        <a asp-action="Delete" asp-route-id="@Model?.Id">Delete</a> <span> | </span>
    }
    <a asp-action="Index">Back to List</a>
</div>

Views/Stocks/Index.cshtml
@model IEnumerable<Gambling_my_beloved.Models.Stock>

@{
    ViewData["Title"] = "All Stocks";
}

<h1 class="display-4">All Stocks</h1>
<hr/>

@if (User.IsInRole(Roles.Administrator))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>   
}

@await Html.PartialAsync("_IndexSearchPartial")

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Symbol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceChange)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceChangePercent)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (Stock item in Model)
    {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="stock-nameplate" style="background-color: @item.Color">
                    @item.Symbol
                </a>
            </td>
            <td>
                <a asp-controller="Companies" asp-action="Details" asp-route-id="@item.Company.Id" class="text-dark no-dec">
                    @Html.DisplayFor(modelItem => item.Company.Name)
                </a>
            </td>
            <td>
                @item.UnitPrice.ToCurrency()
            </td>
            <td>
                @item.PriceChange.ToCurrency()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceChangePercent, "PriceChange")
            </td>
        </tr>
    }
    </tbody>
</table>

Views/Stocks/Transact.cshtml
@using Microsoft.AspNetCore.Identity
@model Transaction
@inject UserManager<ApplicationUser> UserManager

@{
    bool success = (bool)ViewData["Success"];
    string message = (string)ViewData["Message"];

    StockOwnership stockOwnership = Model.StockOwnership;
    Stock stock = stockOwnership.Stock;

    ApplicationUser currentUser = await UserManager.GetUserAsync(User);
    string phrase = (success, Model.Type) switch {
        (true, TransactionType.Buy) => "Bought",
        (true, TransactionType.Sell) => "Sold",
        
        (false, TransactionType.Buy) => "Failed to buy",
        (false, TransactionType.Sell) => "Failed to sell",
        
        _ => throw new ArgumentOutOfRangeException()
    };
}


<div class="alert @(success ? "alert-success" : "alert-danger") alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">
        @phrase
        @Model.Quantity.ToString("N0") share(s) of @stock.Symbol at @stock.UnitPrice.ToCurrency()/share
    </h4>
    <p>@message</p>

    @if (success)
    {
        <hr/>
        <span class="text-secondary">@Model.Date.ToString("yyyy-MM-dd HH:mm:ss")</span>
    }
</div>

<hr/>

<a asp-controller="Stocks" asp-action="Details" asp-route-id="@stock.Id" class="btn btn-primary">Back to Stock</a>